version: '3'
services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - 9000:9000
    command: [server, /data]
    volumes:
      - minio_data:/data
    env_file: .env
    restart: always

volumes:
  minio_data:
    driver: 'local'
